spring:
#        redis:
#          cluster:
#            nodes: 127.0.0.1:6379,127.0.0.1:6479,127.0.0.1:6579,127.0.0.1:6679,127.0.0.1:6779,127.0.0.1:6879

        datasource:
          name: test
          url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false
          username: inte
          password: 123456
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver

people:
        name: helloWorld
        age: 27
        interests: movie,play games,sport
id: 132456
name: test
mybatis:
  mapper-locations: classpath:mapper/*.xml
